### ISSUE TITLE
Notebooksが削除されている

### ISSUE THREAD

**Issue by matsuu** [lawofcycles/apache-iceberg-101-ja#3]
[overall refactor](https://github.com/lawofcycles/apache-iceberg-101-ja/commit/59c8a24ca5d47482cb6fde34800bae5a7f7c5b36)の際にsparkディレクトリをspark-icebergに変更したのと、.gitignoreの [!spark/notebooks](https://github.com/lawofcycles/apache-iceberg-101-ja/blob/59c8a24ca5d47482cb6fde34800bae5a7f7c5b36/.gitignore#L189)の行が更新されなかったことからnotebooksがリポジトリから削除されてしまっているようです。

**Comment by lawofcycles** [comment]
教えていただきありがとうございます。仰る通り、メンテした際にうっかり肝心のノートブックを消してしまっていたようです。  
できるだけ早く直すようにします。

**Comment by lawofcycles** [comment]
復旧しました。
